### ISSUE TITLE
"death" vs. "deauth" typo w/r/t aircrack-ng DOS command

### ISSUE THREAD

**Issue by greyspectrum** [isislovecruft/patternsinthevoid#5]
In the course of writing a short hacky script to automate the attack you mentioned in your post "Broadcast De-auth DOS Attack: Jamming WiFi Networks," I noticed a small typo. You wrote:

`airplay-ng --death 0 -a [BSSID of victim network access point] mon0`

but I think you meant:

`aireplay-ng --deauth 0 -a [BSSID of victim network access point] mon0`

Although, "death" is pretty funny in the context of a DOS command.

**Comment by isislovecruft** [comment]
Hah, that is a funny typo. Thanks for pointing that out!

**Comment by isislovecruft** [comment]
Fixed.
